
name: Flutter Android CI

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.1'
    - name: install 0.5
      run: |
        echo "=============="
        echo "Runner temp DIRECTORY:"
        dir ${{ runner.temp }}
        echo "=============="
        echo "ASR $ANDROID_SDK_ROOT"
        echo "=============="
        echo "AH $ANDROID_HOME"
        echo "=============="
        echo "ASR dir"
        dir $ANDROID_SDK_ROOT
        echo "=============="
    - name: Install Android SDK
      run: |
        mkdir ${{ runner.temp }}/android
        echo "ANDROID_SDK_ROOT=${{ runner.temp }}/android" >> $GITHUB_ENV
        echo "ANDROID_HOME=${{ runner.temp }}/android" >> $GITHUB_ENV
        wget https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip
        unzip commandlinetools-linux-7583922_latest.zip -d ${{ runner.temp }}/android
    - name: install 1.5
      run: |
        echo "=============="
        echo "Runner temp DIRECTORY:"
        dir ${{ runner.temp }}
        echo "=============="        
        echo "ASR $ANDROID_SDK_ROOT"
        echo "=============="
        echo "AH $ANDROID_HOME"
        echo "=============="
        echo "ASR dir"
        dir $ANDROID_SDK_ROOT
        echo "=============="
        #dir ${{ runner.temp }}/cmdline-tools/cmdline-tools
        echo "=============="
        echo "PATH"
        echo $PATH
        echo "=============="
    - name: install 2 - path
      run: |
        echo $ANDROID_SDK_ROOT/cmdline-tools/latest/bin >> $GITHUB_PATH
        #echo ${{ runner.temp }}/cmdline-tools/bin >> $GITHUB_PATH
        #echo ${{ runner.temp }}/cmdline-tools/cmdline-tools/bin >> $GITHUB_PATH
    - name: install 2.5
      run: |
        echo "=============="
        echo "Runner temp DIRECTORY:"
        dir ${{ runner.temp }}
        echo "=============="
        echo "android"
        dir ${{runner.temp}}/android/
        echo "cmdline-tools"
        dir ${{runner.temp}}/android/cmdline-tools/
        echo "bin"
        dir ${{runner.temp}}/android/cmdline-tools/bin
        echo "=============="
        echo "PATH"
        echo $PATH
        echo "=============="
    - name: install 3 - sdk lisences
      run: yes | sdkmanager --licenses
    - name: install 3.1.1 - sdk components - build tools
      run: sdkmanager --sdk_root=${ANDROID_SDK_ROOT} "build-tools;30.0.3"
    - name: install 3.1.2 - sdk components - platform tools
      run: sdkmanager --sdk_root=${ANDROID_SDK_ROOT} "platform-tools"
    - name: install 3.1.3 - sdk components - platform
      run: sdkmanager --sdk_root=${ANDROID_SDK_ROOT} "platforms;android-30"
    - name: install 3.1.4 - sdk components - emulator
      run: sdkmanager --sdk_root=${ANDROID_SDK_ROOT} "emulator"
    - name: install 3.1.5 - sdk components - system images
      run: sdkmanager --sdk_root=${ANDROID_SDK_ROOT} "system-images;android-30;google_apis;x86_64"
    - name: install 3.5
      run: |
        echo "=============="
        echo "Runner temp DIRECTORY:"
        dir ${{ runner.temp }}
        echo "=============="
        echo "ASR $ANDROID_SDK_ROOT"
        echo "=============="
        echo "AH $ANDROID_HOME"
        echo "=============="
        echo "ASR dir"
        dir $ANDROID_SDK_ROOT
        echo "=============="
    - name: Create and start emulator
      run: |
        echo "no" | ${{ runner.temp }}/cmdline-tools/cmdline-tools/bin/avdmanager create avd --force --name testEmulator --package 'system-images;android-30;google_apis;x86_64' --abi google_apis/x86_64 --device "pixel"
        echo "=============="
        $ANDROID_HOME/emulator/emulator -avd testEmulator -no-window -no-audio -no-boot-anim &
        echo "=============="
        $ANDROID_HOME/platform-tools/adb wait-for-device get-serialno
        echo "=============="
        $ANDROID_HOME/platform-tools/adb shell input keyevent 82
    - run: flutter pub get
    - run: flutter devices
    - run: flutter test integration_test -d emulator-5554
        
