
name: Flutter Android CI

on: [push]

jobs:
  build-and-test:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.1'
    - run: flutter pub get
    - run: flutter devices
    - run: flutter test integration_test -d emulator-5554
        
