
name: Flutter Android CI

on:
  push:
    branches:
      testbranch

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.1'
        cache: true
    
    - name: Install Chrome Browser
      uses: browser-actions/setup-chrome@v1
      with:
       chrome-version: stable
      id: setup-chrome
  
    - name: Check Browser version
      run: |
        echo Installed chromium version: ${{ steps.setup-chrome.outputs.chrome-version }}
        ${{ steps.setup-chrome.outputs.chrome-path }} --version
    
    - name: setup chromedriver
      uses: nanasess/setup-chromedriver@v2.2.1

    - name:  Delay
      run: |
        echo "Waiting for Chromedriver to start..."
        sleep 20

    - name: 🪛 Start Chromedriver
      run: |
        export DISPLAY=:99
        chromedriver --url-base=/wd/hub --port=4444 --verbose &
        sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &

    - name: Check Chromedriver Version
      run: chromedriver -v
    
#    - run: flutter pub get
#    - run: flutter devices
#    - run: flutter test integration_test -d windows
        
