
name: Flutter Android CI

on:
  push:
    branches:
      testbranch

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.1'
        cache: true
  
    - run: flutter pub get    

    # - name: Install Chrome Browser
    #   uses: browser-actions/setup-chrome@v1
    #   with:
    #    chrome-version: '119.0.6045.105'
    #   id: setup-chrome
  
    # - name: Check Browser version
    #   run: |
    #     echo Installed chromium version: ${{ steps.setup-chrome.outputs.chrome-version }}
    #     ${{ steps.setup-chrome.outputs.chrome-path }} --version
    
    # - name: setup chromedriver
    #   uses: nanasess/setup-chromedriver@v2.2.1

    # - name:  Delay
    #   run: |
    #     echo "Waiting for Chromedriver to start..."
    #     sleep 20

    # - name: 🪛 Start Chromedriver
    #   run: |
    #     export DISPLAY=:99
    #     chromedriver --url-base=/wd/hub --port=4444 --verbose &
    #     sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &

    # - name: Check Chromedriver Version
    #   run: chromedriver -v

    # - name: Delay
    #   run: |
    #     echo "Waiting for Chromedriver to start..."
    #     sleep 15

    # - name:  Check Chromedriver Port
    #   run: |
    #     lsof -i :4444

    - name: Flutter Doctor
      run: flutter doctor -v
      
    - name: Download and Set up Ninja
      run: |
        wget https://github.com/ninja-build/ninja/releases/download/v1.10.2/ninja-linux.zip
        unzip ninja-linux.zip
        sudo mv ninja /usr/local/bin/
        ninja --version
        
    - name:  Run Integration Test
      run: |
        flutter config --enable-web
        flutter drive --driver=test_driver/integration_test.dart --target=integration_test/widget_test.dart -d linux
    
#    - run: flutter pub get
#    - run: flutter devices
#    - run: flutter test integration_test -d windows
        
